name: SwiftMacros

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  SwiftMacros:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: swift build

    - name: Run tests
      run: swift test